### ISSUE TITLE
Add babel-polyfill to devDependencies in package.json

### ISSUE THREAD

**Issue by seanpharvey** [willowtreeapps/tsx-boilerplate#2]
On initial startup the boilerplate complains that it can't resolve babel-polyfill.

The dependency is specified in the webpack entry point. `npm install babel-polyfill --save-dev` resolved the issue.

Show me how to do a pull request and I'll fix it myself.  Go Trevor!!

**Comment by trevorsenior** [comment]
Fixed in #9
